baseurl = "http://iplaws.cn/"  # End your URL with a `/` trailing slash.
title = "IP Laws，知识产权律师"
copyright = "&copy; 2017 IPlaws.cn"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = "iplaws-cn"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "周才淇律师"
  role = "著作权、商标、专利、商业秘密"
  organization = "泰和泰律师事务所"
  organization_url = "http://www.tahota-lawyer.com"
  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "info@iplaws.cn"
  address = "深圳市福田区福虹路9号世贸广场C座25层"
  office_hours = ""
  phone = "177 2261 8837"
  skype = ""
  wechat = "choicky"
  qq = "85144733"
  telegram = ""
    
  # Enable analytics by entering your Baidu Tongji tracking ID
  baiduTongji = true

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = []
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:info@iplaws.cn"

  [[params.social]]
    icon = "qq"
    icon_pack = "fa"
    link = "tencent://message/?uin=85144733"
    
  [[params.social]]
    icon = "wechat"
    icon_pack = "fa"
    link = "weixin://contacts/profile/choicky"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/choicky"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/choicky"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "首页"
  url = "#about"
  weight = 11

[[menu.main]]
  name = "书籍"
  url = "#publications_selected"
  weight = 21

[[menu.main]]
  name = "文章"
  url = "#posts"
  weight = 31

[[menu.main]]
  name = "案例"
  url = "#projects"
  weight = 41

[[menu.main]]
  name = "类别"
  weight = 51
  
    [[menu.main]]
      name = "著作权"
      url = "tags/著作权"
      parent = "类别"
      weight = 52
    [[menu.main]]
      name = "商标"
      url = "tags/商标"
      parent = "类别"
      weight = 54    
    [[menu.main]]
      name = "外观"
      url = "tags/外观"
      parent = "类别"
      weight = 56
    [[menu.main]]
      name = "专利"
      url = "tags/专利"
      parent = "类别"
      weight = 58
    [[menu.main]]
      name = "商业秘密"
      url = "tags/商业秘密"
      parent = "类别"
      weight = 60

[[menu.main]]
  name = "联系"
  url = "#contact"
  weight = 61

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
